AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CodeBuild template for dotbare, webhook trigger from Github only on Master push

Resources:
  CodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: true
      Description: CodeBuild project for dotbare
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      Name: dotbare
      ServiceRole: !GetAtt ServiceRole.Arn
      Source:
        Location: https://github.com/kazhala/dotbare.git
        ReportBuildStatus: true
        Type: GITHUB
      SourceVersion: master
      Triggers:
        FilterGroups:
          - - Type: HEAD_REF
              Pattern: ^refs/heads/master$
            - Type: EVENT
              Pattern: PUSH,PULL_REQUEST_MERGED
        Webhook: true

  ServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'codebuild.amazonaws.com'
            Action: 'sts:AssumeRole'
      Description: !Sub 'CodeBuild role for ${AWS::StackName}'
      RoleName: !Sub '${AWS::StackName}-codebuild'

  ParameterStorePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub '${AWS::StackName}-codebuild-ssm-access'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'ssm:GetParameters'
            Resource: 'arn:aws:ssm:region:account-id:parameter/dotbare/*'
          - Effect: Allow
            Action:
              - 'kms:Decrypt'
            Resource: 'arn:aws:kms:ap-southeast-2:378756445655:key/51311dc6-8e2d-4139-abdc-5a81261eaa40'
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource:
              - 'arn:aws:logs:ap-southeast-2:378756445655:log-group:/aws/codebuild/dotbare'
              - 'arn:aws:logs:ap-southeast-2:378756445655:log-group:/aws/codebuild/dotbare:*'
      Roles:
        - !Ref ServiceRole
