AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cloudformation template for creating a single dynamoDB table that would take
  throughput, name, keys as parameters on creation time.
Parameters:
  BillingMode:
    Description: billing mode for the table
    Type: String
    Default: PROVISIONED
    AllowedValues:
      - PROVISIONED
      - PAY_PER_REQUEST
    ConstraintDescription: provisioned is recommanded for predictable load
  TableName:
    Description: name of the new table
    Type: String
    Default: NewTable
    MinLength: '3'
    MaxLength: '255'
    AllowedPattern: '^[A-Za-z0-9][-a-zA-Z0-9_\.]*'
    ConstraintDescription: requires name for the new table
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: 5
    MinValue: 5
    MaxValue: 40000
    ConstraintDescription: must be a valid range for DynamoDB throughput
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: 5
    MinValue: 5
    MaxValue: 40000
    ConstraintDescription: must be a valid range for DynamoDB throughput
  PartitionKey:
    Description: partition key name for the table
    Type: String
    Default: PrimaryKey
    MinLength: '1'
    MaxLength: '255'
    ConstraintDescription: table must contain at least one partition key
  PartitionType:
    Description: partition key data type
    Type: String
    Default: S
    AllowedValues:
      - S
      - B
      - N
    ConstraintDescription: string, binary, number
  SortKey:
    Description: sort key name for the table(optional)
    Type: String
    MaxLength: '255'
    ConstraintDescription: optional params
  SortKeyType:
    Description: sort key data type
    Type: String
    Default: S
    AllowedValues:
      - S
      - B
      - N
    ConstraintDescription: string, binary, number
Conditions:
  HasSortKey: !Not [!Equals [!Ref SortKey, ""]]
  Provisioned: !Equals [!Ref BillingMode, PROVISIONED]
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: !Ref BillingMode
      AttributeDefinitions:
        - AttributeName: !Ref PartitionKey
          AttributeType: !Ref PartitionType
        - !If
          - HasSortKey
          - AttributeName: !Ref SortKey
            AttributeType: !Ref SortKeyType
          - !Ref 'AWS::NoValue'
      KeySchema:
        - AttributeName: !Ref PartitionKey
          KeyType: 'HASH'
        - !If
          - HasSortKey
          - AttributeName: !Ref SortKey
            KeyType: 'RANGE'
          - !Ref 'AWS::NoValue'
      ProvisionedThroughput:
        !If
          - Provisioned
          - ReadCapacityUnits: !Ref ReadCapacityUnits
            WriteCapacityUnits: !Ref WriteCapacityUnits
          - !Ref 'AWS::NoValue'
      TableName: !Ref TableName
  WriteCapacityScalableTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    Properties:
      MaxCapacity: 40000
      MinCapacity: 5
      ResourceId: !Join
        - /
        - - table
          - !Ref DynamoDBTable
      RoleARN: arn:aws:iam::989747322090:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb
  ReadCapacityScalableTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    Properties:
      MaxCapacity: 40000
      MinCapacity: 5
      ResourceId: !Join
        - /
        - - table
          - !Ref DynamoDBTable
      RoleARN: arn:aws:iam::989747322090:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      ServiceNamespace: dynamodb
  WriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: WriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
  ReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ReadCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization
