AWSTemplateFormatVersion: 2010-09-09
Description: >-
  s3 cloudformation template that would create a s3 bucket for
  cloudformation template storage
Parameters:
  BucketName:
    Description: Name of the bucket, be random
    Type: String
    MinLength: '6'
    MaxLength: '255'
    AllowedPattern: '[a-z0-9]*[-a-z0-9]*'
  AccessControl:
    Description: Access control setting
    Type: String
    Default: Private
    AllowedValues:
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthenticatedRead
      - LogDeliveryWrite
      - BucketOwnerRead
      - BucketOwnerFullControl
      - AwsExecRead
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: !Ref AccessControl
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
Outputs:
  S3BucketName:
    Description: Name of the bucket
    Value: !Ref S3Bucket
