AWSTemplateFormatVersion: 2010-09-09
Description: >-
  A cloudformation template for creating my personal default security groups
  used within any vpc
Parameters:
  VpcId:
    Description: The vpc id of which this sg should be in, skip this value to use default VPC
    Type: String
  NamePrefix:
    Description: Prefix for the security group, specify this when creating through nested stack
    Type: String
  TurrmurraSSH:
    Description: The IP address range to access through the SG via ssh
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  EppingSSH:
    Description: The IP address range to access through the SG via ssh
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  RemoteSSH:
    Description: The IP address range to access through the SG via ssh
    Type: String
    MaxLength: '18'
    AllowedPattern: '((\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})){0,1}'
Conditions:
  RemoteLocation: !Not [!Equals ['', !Ref RemoteSSH]]
  NonDefaultVPC: !Not [!Equals ['', !Ref VpcId]]
Resources:
  DefaultSSHSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for controlling access to FLEX_EC2 instances
      SecurityGroupIngress: !If
        - RemoteLocation
        - - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Ref TurrmurraSSH
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Ref EppingSSH
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Ref RemoteSSH
        - - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Ref TurrmurraSSH
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Ref EppingSSH
      VpcId: !If [NonDefaultVPC, !Ref VpcId, !Ref 'AWS::NoValue']
      GroupName: !If [NonDefaultVPC, !Sub '${NamePrefix}-ssh', 'default-ssh']
      Tags:
        - Key: Name
          Value: !If
            - NonDefaultVPC
            - !Sub '${NamePrefix}-ssh'
            - 'default-ssh'
  DefaultWebServerSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: SG to attach to a webserver
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      VpcId: !If [NonDefaultVPC, !Ref VpcId, !Ref 'AWS::NoValue']
      GroupName:
        !If [NonDefaultVPC, !Sub '${NamePrefix}-webserver', 'default-webserver']
      Tags:
        - Key: Name
          Value: !If
            - NonDefaultVPC
            - !Sub '${NamePrefix}-webserver'
            - 'default-webserver'
Outputs:
  DefaultSSHSG:
    Description: The default ssh security group id for EC2 import reference
    Value: !GetAtt DefaultSSHSG.GroupId
  DefaultWebServerSG:
    Description: The default webserver security group id for EC2 import reference
    Value: !GetAtt DefaultWebServerSG.GroupId
