name: Lint
on: [push]

jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cfn-lint
        uses: scottbrenner/cfn-lint-action@v2
        with:
          args: '**/*.yaml'
